// Data file - separated to avoid exposure in dev tools
import { TechItem } from "./tech-stack";

export const techStack: TechItem[] = [
  // Languages
  { name: "JavaScript", icon: "🟨", category: "language" },
  { name: "TypeScript", icon: "🔷", category: "language" },
  { name: "Python", icon: "🐍", category: "language" },
  { name: "Java", icon: "☕", category: "language" },
  { name: "C#", icon: "💜", category: "language" },
  { name: "C++", icon: "⚡", category: "language" },
  { name: "C", icon: "©️", category: "language" },
  { name: "Go", icon: "🐹", category: "language" },
  { name: "Rust", icon: "🦀", category: "language" },
  { name: "Ruby", icon: "💎", category: "language" },
  { name: "PHP", icon: "🐘", category: "language" },
  { name: "Swift", icon: "🍎", category: "language" },
  { name: "Kotlin", icon: "🟣", category: "language" },
  { name: "Scala", icon: "🔴", category: "language" },
  { name: "R", icon: "📊", category: "language" },
  { name: "Dart", icon: "🎯", category: "language" },
  { name: "Elixir", icon: "💧", category: "language" },
  { name: "Haskell", icon: "λ", category: "language" },
  { name: "Lua", icon: "🌙", category: "language" },
  { name: "Perl", icon: "🐪", category: "language" },
  { name: "Shell", icon: "🐚", category: "language" },
  { name: "Bash", icon: "💲", category: "language" },
  { name: "PowerShell", icon: "🔵", category: "language" },

  // Frontend
  { name: "React", icon: "⚛️", category: "frontend" },
  { name: "Vue.js", icon: "💚", category: "frontend" },
  { name: "Angular", icon: "🅰️", category: "frontend" },
  { name: "Svelte", icon: "🔥", category: "frontend" },
  { name: "Next.js", icon: "▲", category: "frontend" },
  { name: "Nuxt.js", icon: "💚", category: "frontend" },
  { name: "Remix", icon: "💿", category: "frontend" },
  { name: "Astro", icon: "🚀", category: "frontend" },
  { name: "Solid.js", icon: "💠", category: "frontend" },
  { name: "Qwik", icon: "⚡", category: "frontend" },
  { name: "HTML", icon: "🌐", category: "frontend" },
  { name: "CSS", icon: "🎨", category: "frontend" },
  { name: "Sass", icon: "💅", category: "frontend" },
  { name: "Tailwind CSS", icon: "🌊", category: "frontend" },
  { name: "Bootstrap", icon: "🅱️", category: "frontend" },
  { name: "Material UI", icon: "Ⓜ️", category: "frontend" },
  { name: "Chakra UI", icon: "⚡", category: "frontend" },
  { name: "Styled Components", icon: "💅", category: "frontend" },
  { name: "Framer Motion", icon: "🎬", category: "frontend" },
  { name: "Three.js", icon: "🎮", category: "frontend" },
  { name: "D3.js", icon: "📈", category: "frontend" },
  { name: "jQuery", icon: "📜", category: "frontend" },
  { name: "Webpack", icon: "📦", category: "frontend" },
  { name: "Vite", icon: "⚡", category: "frontend" },
  { name: "Turbopack", icon: "🚀", category: "frontend" },

  // Backend
  { name: "Node.js", icon: "💚", category: "backend" },
  { name: "Express", icon: "🚂", category: "backend" },
  { name: "Fastify", icon: "⚡", category: "backend" },
  { name: "NestJS", icon: "🐱", category: "backend" },
  { name: "Django", icon: "🎸", category: "backend" },
  { name: "Flask", icon: "🍶", category: "backend" },
  { name: "FastAPI", icon: "⚡", category: "backend" },
  { name: "Spring Boot", icon: "🍃", category: "backend" },
  { name: "Laravel", icon: "🔶", category: "backend" },
  { name: "Rails", icon: "🛤️", category: "backend" },
  { name: "ASP.NET", icon: "🔷", category: "backend" },
  { name: ".NET", icon: "🟣", category: "backend" },
  { name: "GraphQL", icon: "◈", category: "backend" },
  { name: "REST API", icon: "🔗", category: "backend" },
  { name: "tRPC", icon: "🔷", category: "backend" },
  { name: "Prisma", icon: "🔺", category: "backend" },
  { name: "Drizzle", icon: "💧", category: "backend" },

  // Database
  { name: "PostgreSQL", icon: "🐘", category: "database" },
  { name: "MySQL", icon: "🐬", category: "database" },
  { name: "MongoDB", icon: "🍃", category: "database" },
  { name: "Redis", icon: "🔴", category: "database" },
  { name: "SQLite", icon: "📁", category: "database" },
  { name: "Supabase", icon: "⚡", category: "database" },
  { name: "Firebase", icon: "🔥", category: "database" },
  { name: "DynamoDB", icon: "📊", category: "database" },
  { name: "Cassandra", icon: "👁️", category: "database" },
  { name: "Neo4j", icon: "🔵", category: "database" },
  { name: "Elasticsearch", icon: "🔍", category: "database" },
  { name: "PlanetScale", icon: "🌍", category: "database" },
  { name: "Neon", icon: "💡", category: "database" },
  { name: "Turso", icon: "🐢", category: "database" },

  // DevOps & Cloud
  { name: "AWS", icon: "☁️", category: "devops" },
  { name: "Google Cloud", icon: "🌈", category: "devops" },
  { name: "Azure", icon: "🔷", category: "devops" },
  { name: "Vercel", icon: "▲", category: "devops" },
  { name: "Netlify", icon: "🌐", category: "devops" },
  { name: "Cloudflare", icon: "☁️", category: "devops" },
  { name: "Docker", icon: "🐳", category: "devops" },
  { name: "Kubernetes", icon: "☸️", category: "devops" },
  { name: "Terraform", icon: "🏗️", category: "devops" },
  { name: "GitHub Actions", icon: "🔄", category: "devops" },
  { name: "Jenkins", icon: "🤖", category: "devops" },
  { name: "CircleCI", icon: "⭕", category: "devops" },
  { name: "Linux", icon: "🐧", category: "devops" },
  { name: "Nginx", icon: "🟢", category: "devops" },
  { name: "Apache", icon: "🪶", category: "devops" },

  // Mobile
  { name: "React Native", icon: "📱", category: "mobile" },
  { name: "Flutter", icon: "🦋", category: "mobile" },
  { name: "iOS", icon: "🍎", category: "mobile" },
  { name: "Android", icon: "🤖", category: "mobile" },
  { name: "Expo", icon: "📲", category: "mobile" },
  { name: "Ionic", icon: "⚡", category: "mobile" },
  { name: "Capacitor", icon: "🔌", category: "mobile" },

  // Tools
  { name: "Git", icon: "📚", category: "tool" },
  { name: "GitHub", icon: "🐙", category: "tool" },
  { name: "GitLab", icon: "🦊", category: "tool" },
  { name: "VS Code", icon: "💙", category: "tool" },
  { name: "Vim", icon: "📝", category: "tool" },
  { name: "Neovim", icon: "💚", category: "tool" },
  { name: "Figma", icon: "🎨", category: "tool" },
  { name: "Postman", icon: "📮", category: "tool" },
  { name: "Insomnia", icon: "😴", category: "tool" },
  { name: "Jest", icon: "🃏", category: "tool" },
  { name: "Vitest", icon: "⚡", category: "tool" },
  { name: "Cypress", icon: "🌲", category: "tool" },
  { name: "Playwright", icon: "🎭", category: "tool" },
  { name: "Storybook", icon: "📖", category: "tool" },
  { name: "ESLint", icon: "🔍", category: "tool" },
  { name: "Prettier", icon: "✨", category: "tool" },

  // AI/ML
  { name: "TensorFlow", icon: "🧠", category: "other" },
  { name: "PyTorch", icon: "🔥", category: "other" },
  { name: "OpenAI", icon: "🤖", category: "other" },
  { name: "LangChain", icon: "🔗", category: "other" },
  { name: "Hugging Face", icon: "🤗", category: "other" },
  { name: "Scikit-learn", icon: "📊", category: "other" },
  { name: "Pandas", icon: "🐼", category: "other" },
  { name: "NumPy", icon: "🔢", category: "other" },

  // Other
  { name: "Stripe", icon: "💳", category: "other" },
  { name: "Twilio", icon: "📞", category: "other" },
  { name: "SendGrid", icon: "📧", category: "other" },
  { name: "Auth0", icon: "🔐", category: "other" },
  { name: "Clerk", icon: "👤", category: "other" },
  { name: "Socket.io", icon: "🔌", category: "other" },
  { name: "WebSockets", icon: "🌐", category: "other" },
  { name: "RabbitMQ", icon: "🐰", category: "other" },
  { name: "Kafka", icon: "📨", category: "other" },
];

export const techCategories = [
  { value: "language", label: "Languages" },
  { value: "frontend", label: "Frontend" },
  { value: "backend", label: "Backend" },
  { value: "database", label: "Database" },
  { value: "devops", label: "DevOps & Cloud" },
  { value: "mobile", label: "Mobile" },
  { value: "tool", label: "Tools" },
  { value: "other", label: "Other" },
] as const;
