// Icon mapping for tech stack - maps to SVGs in /public/icons/tech/

export interface TechIconMapping {
  name: string;
  filename: string;
}

export const techIcons: TechIconMapping[] = [
  // === LANGUAGES ===
  { name: "JavaScript", filename: "javascript-original.svg" },
  { name: "TypeScript", filename: "typescript-original.svg" },
  { name: "Python", filename: "python-original.svg" },
  { name: "Java", filename: "java-original.svg" },
  { name: "C#", filename: "csharp-original.svg" },
  { name: "C++", filename: "cplusplus-original.svg" },
  { name: "C", filename: "c-original.svg" },
  { name: "Go", filename: "go-original.svg" },
  { name: "Rust", filename: "rust-plain.svg" },
  { name: "PHP", filename: "php-original.svg" },
  { name: "Swift", filename: "swift-original.svg" },
  { name: "Kotlin", filename: "kotlin-original.svg" },
  { name: "Scala", filename: "scala-original.svg" },
  { name: "R", filename: "r-original.svg" },
  { name: "Dart", filename: "dart-original.svg" },
  { name: "Elixir", filename: "elixir-original.svg" },
  { name: "Haskell", filename: "haskell-original.svg" },
  { name: "Lua", filename: "lua-original.svg" },
  { name: "Perl", filename: "perl-original.svg" },
  { name: "Bash", filename: "bash-original.svg" },
  { name: "Clojure", filename: "clojure-original.svg" },
  { name: "Erlang", filename: "erlang-original.svg" },
  { name: "F#", filename: "fsharp-original.svg" },
  { name: "Julia", filename: "julia-original.svg" },
  { name: "Objective-C", filename: "objectivec-plain.svg" },
  { name: "OCaml", filename: "ocaml-original.svg" },
  { name: "Solidity", filename: "solidity-original.svg" },
  { name: "Zig", filename: "zig-original.svg" },
  { name: "Crystal", filename: "crystal-original.svg" },
  { name: "Groovy", filename: "groovy-original.svg" },
  { name: "CoffeeScript", filename: "coffeescript-original.svg" },

  // === FRONTEND ===
  { name: "React", filename: "react-original.svg" },
  { name: "Vue.js", filename: "vuejs-original.svg" },
  { name: "Angular", filename: "angularjs-original.svg" },
  { name: "Svelte", filename: "svelte-original.svg" },
  { name: "Next.js", filename: "nextjs-original.svg" },
  { name: "Nuxt.js", filename: "nuxtjs-original.svg" },
  { name: "HTML", filename: "html5-original.svg" },
  { name: "CSS", filename: "css3-original.svg" },
  { name: "Sass", filename: "sass-original.svg" },
  { name: "Tailwind CSS", filename: "tailwindcss-plain.svg" },
  { name: "Bootstrap", filename: "bootstrap-original.svg" },
  { name: "Material UI", filename: "materialui-original.svg" },
  { name: "Three.js", filename: "threejs-original.svg" },
  { name: "D3.js", filename: "d3js-original.svg" },
  { name: "jQuery", filename: "jquery-original.svg" },
  { name: "Webpack", filename: "webpack-original.svg" },
  { name: "Babel", filename: "babel-original.svg" },
  { name: "Gatsby", filename: "gatsby-original.svg" },
  { name: "Ember", filename: "ember-original-wordmark.svg" },
  { name: "Backbone.js", filename: "backbonejs-original.svg" },
  { name: "Bulma", filename: "bulma-plain.svg" },
  { name: "Electron", filename: "electron-original.svg" },
  { name: "Less", filename: "less-plain-wordmark.svg" },
  { name: "Stylus", filename: "stylus-original.svg" },
  { name: "Handlebars", filename: "handlebars-original.svg" },
  { name: "Eleventy", filename: "eleventy-original.svg" },
  { name: "Hugo", filename: "hugo-original.svg" },
  { name: "Vuetify", filename: "vuetify-original.svg" },

  // === BACKEND ===
  { name: "Node.js", filename: "nodejs-original.svg" },
  { name: "Express", filename: "express-original.svg" },
  { name: "NestJS", filename: "nestjs-plain.svg" },
  { name: "Django", filename: "django-plain.svg" },
  { name: "Flask", filename: "flask-original.svg" },
  { name: "FastAPI", filename: "fastapi-original.svg" },
  { name: "Spring Boot", filename: "spring-original.svg" },
  { name: "Laravel", filename: "laravel-plain.svg" },
  { name: "Rails", filename: "rails-plain.svg" },
  { name: ".NET", filename: "dot-net-original.svg" },
  { name: "GraphQL", filename: "graphql-plain.svg" },
  { name: "Phoenix", filename: "phoenix-original.svg" },
  { name: "CakePHP", filename: "cakephp-original.svg" },
  { name: "CodeIgniter", filename: "codeigniter-plain.svg" },
  { name: "Symfony", filename: "symfony-original.svg" },
  { name: "AdonisJS", filename: "adonisjs-original.svg" },
  { name: "Feathers", filename: "feathersjs-original.svg" },

  // === DATABASE ===
  { name: "PostgreSQL", filename: "postgresql-original.svg" },
  { name: "MySQL", filename: "mysql-original.svg" },
  { name: "MongoDB", filename: "mongodb-original.svg" },
  { name: "Redis", filename: "redis-original.svg" },
  { name: "SQLite", filename: "sqlite-original.svg" },
  { name: "Firebase", filename: "firebase-plain.svg" },
  { name: "Neo4j", filename: "neo4j-original.svg" },
  { name: "Elasticsearch", filename: "elasticsearch.svg" },
  { name: "CouchDB", filename: "couchdb-original.svg" },
  { name: "Oracle", filename: "oracle-original.svg" },
  { name: "MS SQL Server", filename: "microsoftsqlserver-plain.svg" },
  { name: "Sequelize", filename: "sequelize-original.svg" },
  { name: "SQLAlchemy", filename: "sqlalchemy-original.svg" },
  { name: "RocksDB", filename: "rocksdb-plain.svg" },
  { name: "ArangoDB", filename: "ArrangoDB.svg" },
  { name: "InfluxDB", filename: "influxdb_logo.svg" },

  // === DEVOPS & CLOUD ===
  { name: "AWS", filename: "amazonwebservices-original.svg" },
  { name: "Google Cloud", filename: "googlecloud-original.svg" },
  { name: "Azure", filename: "azure-original.svg" },
  { name: "Docker", filename: "docker-original.svg" },
  { name: "Kubernetes", filename: "kubernetes-plain.svg" },
  { name: "Terraform", filename: "terraform-original.svg" },
  { name: "Jenkins", filename: "jenkins-original.svg" },
  { name: "CircleCI", filename: "circleci-plain.svg" },
  { name: "Linux", filename: "linux-original.svg" },
  { name: "Nginx", filename: "nginx-original.svg" },
  { name: "Apache", filename: "apache-original.svg" },
  { name: "Heroku", filename: "heroku-original.svg" },
  { name: "DigitalOcean", filename: "digitalocean-original.svg" },
  { name: "Ansible", filename: "ansible-original.svg" },
  { name: "Vagrant", filename: "vagrant-original.svg" },
  { name: "Grafana", filename: "grafana-original.svg" },
  { name: "Prometheus", filename: "prometheus-original.svg" },
  { name: "ArgoCD", filename: "argocd-original.svg" },
  { name: "Packer", filename: "packer-original.svg" },
  { name: "Podman", filename: "podman-original.svg" },
  { name: "K3s", filename: "k3s-original.svg" },
  { name: "Travis CI", filename: "travis-plain.svg" },
  { name: "Tomcat", filename: "tomcat-original.svg" },
  { name: "uWSGI", filename: "uwsgi-original.svg" },
  { name: "Fluentd", filename: "Fluentd_icon.svg" },
  { name: "Kafka", filename: "apachekafka-original.svg" },

  // === MOBILE ===
  { name: "Flutter", filename: "flutter-original.svg" },
  { name: "Android", filename: "android-original.svg" },
  { name: "Ionic", filename: "ionic-original.svg" },
  { name: "Xamarin", filename: "xamarin-original.svg" },

  // === TOOLS ===
  { name: "Git", filename: "git-original.svg" },
  { name: "GitHub", filename: "github-original.svg" },
  { name: "GitLab", filename: "gitlab-original.svg" },
  { name: "VS Code", filename: "vscode-original.svg" },
  { name: "Vim", filename: "vim-original.svg" },
  { name: "Figma", filename: "figma-original.svg" },
  { name: "Jest", filename: "jest-plain.svg" },
  { name: "Storybook", filename: "storybook-original.svg" },
  { name: "ESLint", filename: "eslint-original.svg" },
  { name: "Bitbucket", filename: "bitbucket-original.svg" },
  { name: "Jira", filename: "jira-original.svg" },
  { name: "Confluence", filename: "confluence-original.svg" },
  { name: "Slack", filename: "slack-original.svg" },
  { name: "Trello", filename: "trello-plain.svg" },
  { name: "IntelliJ", filename: "intellij-original.svg" },
  { name: "WebStorm", filename: "webstorm-original.svg" },
  { name: "PyCharm", filename: "pycharm-original.svg" },
  { name: "PHPStorm", filename: "phpstorm-original.svg" },
  { name: "RubyMine", filename: "rubymine-original.svg" },
  { name: "Android Studio", filename: "androidstudio-original.svg" },
  { name: "XCode", filename: "xcode-original.svg" },
  { name: "Atom", filename: "atom-original.svg" },
  { name: "Selenium", filename: "selenium-original.svg" },
  { name: "Cucumber", filename: "cucumber-plain.svg" },
  { name: "Mocha", filename: "mocha-plain.svg" },
  { name: "Jasmine", filename: "jasmine-plain.svg" },
  { name: "Karma", filename: "karma-original.svg" },
  { name: "Protractor", filename: "protractor-plain.svg" },
  { name: "RSpec", filename: "rspec-original.svg" },
  { name: "pytest", filename: "pytest-original.svg" },
  { name: "Gatling", filename: "gatling-plain.svg" },
  { name: "CMake", filename: "cmake-original.svg" },
  { name: "Gradle", filename: "gradle-plain.svg" },
  { name: "npm", filename: "npm-original-wordmark.svg" },
  { name: "Yarn", filename: "yarn-original.svg" },
  { name: "Composer", filename: "composer-original.svg" },
  { name: "NuGet", filename: "nuget-original.svg" },
  { name: "SSH", filename: "ssh-original.svg" },
  { name: "PuTTY", filename: "putty-original.svg" },
  { name: "FileZilla", filename: "filezilla-plain.svg" },
  { name: "SourceTree", filename: "sourcetree-original.svg" },
  { name: "TortoiseGit", filename: "tortoisegit-original.svg" },
  { name: "Tower", filename: "towergit-original.svg" },

  // === DESIGN ===
  { name: "Photoshop", filename: "photoshop-plain.svg" },
  { name: "Illustrator", filename: "illustrator-plain.svg" },
  { name: "After Effects", filename: "aftereffects-original.svg" },
  { name: "Premiere Pro", filename: "premierepro-original.svg" },
  { name: "XD", filename: "xd-plain.svg" },
  { name: "Sketch", filename: "sketch-original.svg" },
  { name: "Blender", filename: "blender-original.svg" },
  { name: "GIMP", filename: "gimp-original.svg" },
  { name: "Inkscape", filename: "inkscape-original.svg" },
  { name: "Maya", filename: "maya-original.svg" },
  { name: "Canva", filename: "canva-original.svg" },
  { name: "Behance", filename: "behance-original.svg" },
  { name: "Webflow", filename: "webflow-original.svg" },

  // === AI/ML ===
  { name: "TensorFlow", filename: "tensorflow-original.svg" },
  { name: "PyTorch", filename: "pytorch-original.svg" },
  { name: "Pandas", filename: "pandas-original.svg" },
  { name: "NumPy", filename: "numpy-original.svg" },
  { name: "Jupyter", filename: "jupyter-original.svg" },
  { name: "Anaconda", filename: "anaconda-original.svg" },
  { name: "OpenCV", filename: "opencv-original.svg" },
  { name: "Kaggle", filename: "kaggle-original.svg" },
  { name: "MATLAB", filename: "matlab-original.svg" },
  { name: "R Studio", filename: "rstudio-original.svg" },
  { name: "SPSS", filename: "spss-original.svg" },
  { name: "Minitab", filename: "minitab-original.svg" },
  { name: "LabVIEW", filename: "labview-original.svg" },
  { name: "NetworkX", filename: "networkx-original.svg" },

  // === CMS & E-COMMERCE ===
  { name: "WordPress", filename: "wordpress-original.svg" },
  { name: "Drupal", filename: "drupal-original.svg" },
  { name: "Magento", filename: "magento-original.svg" },
  { name: "WooCommerce", filename: "woocommerce-original.svg" },
  { name: "Shopware", filename: "shopware-original.svg" },
  { name: "TYPO3", filename: "typo3-original.svg" },
  { name: "Moodle", filename: "moodle-original.svg" },

  // === GAME DEVELOPMENT ===
  { name: "Unity", filename: "unity-original.svg" },
  { name: "Unreal Engine", filename: "unrealengine-original.svg" },
  { name: "Godot", filename: "godot-original.svg" },
  { name: "OpenGL", filename: "opengl-original.svg" },
  { name: "SDL", filename: "sdl-original.svg" },

  // === OTHER ===
  { name: "Socket.io", filename: "socketio-original.svg" },
  { name: "Arduino", filename: "arduino-original.svg" },
  { name: "Raspberry Pi", filename: "raspberrypi-original.svg" },
  { name: "Salesforce", filename: "salesforce-original.svg" },
  { name: "AppWrite", filename: "appwrite-original.svg" },
  { name: "Discord.js", filename: "discordjs-original.svg" },
  { name: "Processing", filename: "processing-original.svg" },
  { name: "Haxe", filename: "haxe-original.svg" },
  { name: "GCC", filename: "gcc-original.svg" },
  { name: "Deno", filename: "denojs-original.svg" },

  // === OS ===
  { name: "Ubuntu", filename: "ubuntu-plain.svg" },
  { name: "Debian", filename: "debian-original.svg" },
  { name: "CentOS", filename: "centos-original.svg" },
  { name: "Fedora", filename: "fedora-original.svg" },
  { name: "Red Hat", filename: "redhat-original.svg" },
  { name: "openSUSE", filename: "opensuse-original.svg" },
  { name: "NixOS", filename: "nixos-original.svg" },
  { name: "Gentoo", filename: "gentoo-plain.svg" },
  { name: "Windows", filename: "windows8-original.svg" },
  { name: "Unix", filename: "unix-original.svg" },

  // === BROWSERS ===
  { name: "Chrome", filename: "chrome-original.svg" },
  { name: "Firefox", filename: "firefox-original.svg" },
  { name: "Safari", filename: "safari-original.svg" },
  { name: "Opera", filename: "opera-original.svg" },
];

// Helper function to get icon by tech name
export function getTechIcon(name: string): TechIconMapping | undefined {
  return techIcons.find(
    (icon) => icon.name.toLowerCase() === name.toLowerCase()
  );
}

// Get icon URL or null if not available
export function getTechIconUrl(name: string): string | null {
  const icon = getTechIcon(name);
  return icon ? `/icons/tech/${icon.filename}` : null;
}

// Check if tech has an icon
export function hasTechIcon(name: string): boolean {
  return getTechIcon(name) !== undefined;
}
